# Generated by Django 3.2.12 on 2022-03-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_123', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='fullname',
            field=models.CharField(default='default', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(default='default', max_length=10),
        ),
    ]
